export const GET_ITEM_DETAILS = 'GET_ITEM_DETAILS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_ITEMS = 'GET_ITEMS';
export const ITEMS_RECEIVED = 'ITEMS_RECEIVED';
export const ITEM_CATEGORIES_RECEIVED = 'ITEM_CATEGORIES_RECEIVED';
export const ITEM_DETAILS_RECEIVED = 'ITEM_DETAILS_RECEIVED';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';
